{{- $templates_path := printf "cue/traits/*.cue" -}}
{{ range $path, $_ := .Files.Glob $templates_path }}
{{ $cue_template := $.Files.Get $path | toYaml }}
{{ $name := trimSuffix ".cue" (base $path) }}
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  name: {{ $name }}
spec:
  podDisruptive: false
  schematic:
    cue:
      template:
      {{ $cue_template | indent 8 }}
---
{{ end }}
