apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  labels:
    fluxcd.io/system: kubevela
  name: vela-apps
  namespace: vela-system
spec:
  force: false
  interval: 1m
  path: "./apps"
  prune: true
  sourceRef:
    kind: GitRepository
    name: vela-apps
    namespace: flux-bootstrap
  suspend: false
