apiVersion: v2
name: flux-monitoring
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: kube-prometheus-stack
    version: 54.2.2
    repository: https://prometheus-community.github.io/helm-charts
  - name: loki-stack
    version: 2.9.11
    repository: https://grafana.github.io/helm-charts
